class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'PashuSwasthya',
      'app_subtitle': 'Cattle Health Assistant',
      'breed_disease_detection': 'Breed & Disease Detection',
      'breed_disease_subtitle': 'Identify breed first, then detect diseases automatically.',
      'treatment_guide': 'Treatment Guide',
      'treatment_guide_subtitle': 'Access offline guides for common treatments.',
      'vet_help': 'Vet Help',
      'vet_help_subtitle': 'Connect with a certified vet for expert advice.',
      'vet_connect_coming_soon': 'Vet Connect feature coming soon!',
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'help_support': 'Help & Support',
      'about': 'About',
      'select_language': 'Select Language',
      'continue_btn': 'Continue',
      'choose_language': 'Choose Your Language',
      'home': 'Home',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'analyze': 'Analyze',
      'result': 'Result',
      'unknown': 'Unknown',
      'notifications': 'Notifications',
      'account': 'Account',
      'offline_data_update': 'Offline Data Update',
      'save_user_info': 'Save User Info',
      'clear_cache': 'Clear Cache',
      'general': 'General',
      'data_offline': 'Data & Offline',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'are_you_sure_clear_cache': 'Are you sure you want to clear the cache?',
      'please_select_language': 'Please select a language',
      'breed_detection': 'Breed Detection',
      'breed_result': 'Breed Result',
      'disease_detection': 'Disease Detection',
      'detection_results': 'Detection Results',
      'upload_cattle_image': 'Upload image of your cattle for breed identification',
      'detect_breed': 'Detect Breed',
      'detecting': 'Detecting...',
      'breed_identified': 'Breed Identified',
      'confidence': 'Confidence',
      'continue_disease_detection': 'Continue to Disease Detection',
      'upload_disease_image': 'Upload image of the diseased area',
      'analyze_disease': 'Analyze Disease',
      'analyzing': 'Analyzing...',
      'disease_status': 'Disease Status',
      'overall_accuracy': 'Overall Accuracy',
      'no_disease_detected': 'No disease detected',
      'view_treatment': 'View Treatment',
      'start_new_detection': 'Start New Detection',
      'camera_permission_required': 'Camera permission is required',
      'please_capture_image': 'Please capture or upload image first',
      'breed_detection_failed': 'Breed detection failed',
      'disease_detection_failed': 'Disease detection failed',
      'treatment_guides': 'Treatment Guides',
      'symptoms': 'Symptoms',
      'treatment_steps': 'Treatment Steps',
      'precautions': 'Precautions',
      'first_aid': 'First Aid',
      'emergency_severe_disease': 'EMERGENCY - Severe Disease Detected',
      'contact_vet_immediately': 'Contact a veterinarian immediately:',
      'cannot_make_call': 'Cannot make call',
      'disease_fmd': 'Foot and Mouth Disease',
      'disease_mastitis': 'Mastitis',
      'disease_lsd': 'Lumpy Skin Disease',
      'disease_brucellosis': 'Brucellosis',
      'disease_anthrax': 'Anthrax',
      'voice_disease_prediction': 'Voice Disease Prediction',
      'listening_describe_symptoms': 'Listening... Describe your cattle symptoms',
      'analyzing_symptoms': 'Analyzing symptoms...',
      'tap_mic_describe': 'Tap the microphone to describe the cattle health',
      'microphone_permission_required': 'Microphone permission is required',
      'error': 'Error',
      'speech_recognition_not_available': 'Speech recognition not available',
      'identified_disease': 'Identified Disease',
      'matched_symptoms': 'Matched Symptoms',
      'all_symptoms': 'All Symptoms',
      'view_treatment_guide': 'View Treatment Guide',
      'stop_recording': 'Stop Recording',
      'stop': 'Stop',
      'start': 'Start',
      'save': 'Save',
      'description_saved': 'Description saved successfully',
      'no_disease_identified': 'No disease identified. Please describe more symptoms.',
      'your_description_here': 'Your description will appear here...',
      'describe_symptoms_info': 'Describe your cattle symptoms. We will automatically identify the disease.',
    },
    'hi': {
      'app_name': 'पशु स्वास्थ्य',
      'app_subtitle': 'पशु स्वास्थ्य सहायक',
      'breed_disease_detection': 'नस्ल और रोग पहचान',
      'breed_disease_subtitle': 'पहले नस्ल की पहचान करें, फिर रोगों का पता लगाएं।',
      'treatment_guide': 'उपचार गाइड',
      'treatment_guide_subtitle': 'सामान्य उपचारों के लिए ऑफ़लाइन गाइड देखें।',
      'vet_help': 'पशु चिकित्सक सहायता',
      'vet_help_subtitle': 'विशेषज्ञ सलाह के लिए प्रमाणित पशु चिकित्सक से जुड़ें।',
      'vet_connect_coming_soon': 'वेट कनेक्ट सुविधा जल्द आ रही है!',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'dark_mode': 'डार्क मोड',
      'help_support': 'सहायता और समर्थन',
      'about': 'के बारे में',
      'select_language': 'भाषा चुनें',
      'continue_btn': 'जारी रखें',
      'choose_language': 'अपनी भाषा चुनें',
      'home': 'होम',
      'camera': 'कैमरा',
      'gallery': 'गैलरी',
      'analyze': 'विश्लेषण करें',
      'result': 'परिणाम',
      'unknown': 'अज्ञात',
      'notifications': 'सूचनाएं',
      'account': 'खाता',
      'offline_data_update': 'ऑफ़लाइन डेटा अपडेट',
      'save_user_info': 'उपयोगकर्ता जानकारी सहेजें',
      'clear_cache': 'कैश साफ़ करें',
      'general': 'सामान्य',
      'data_offline': 'डेटा और ऑफ़लाइन',
      'cancel': 'रद्द करें',
      'clear': 'साफ़ करें',
      'are_you_sure_clear_cache': 'क्या आप वाकई कैश साफ़ करना चाहते हैं?',
      'please_select_language': 'कृपया एक भाषा चुनें',
      'breed_detection': 'नस्ल पहचान',
      'breed_result': 'नस्ल परिणाम',
      'disease_detection': 'रोग पहचान',
      'detection_results': 'पहचान परिणाम',
      'upload_cattle_image': 'नस्ल की पहचान के लिए अपने मवेशी की छवि अपलोड करें',
      'detect_breed': 'नस्ल पहचानें',
      'detecting': 'पहचान की जा रही है...',
      'breed_identified': 'पहचानी गई नस्ल',
      'confidence': 'विश्वास',
      'continue_disease_detection': 'रोग पहचान के लिए जारी रखें',
      'upload_disease_image': 'रोगग्रस्त क्षेत्र की छवि अपलोड करें',
      'analyze_disease': 'रोग का विश्लेषण करें',
      'analyzing': 'विश्लेषण किया जा रहा है...',
      'disease_status': 'रोग की स्थिति',
      'overall_accuracy': 'कुल सटीकता',
      'no_disease_detected': 'कोई रोग नहीं मिला',
      'view_treatment': 'उपचार देखें',
      'start_new_detection': 'नई पहचान शुरू करें',
      'camera_permission_required': 'कैमरा अनुमति आवश्यक है',
      'please_capture_image': 'कृपया पहले छवि कैप्चर करें या अपलोड करें',
      'breed_detection_failed': 'नस्ल पहचान विफल',
      'disease_detection_failed': 'रोग पहचान विफल',
      'treatment_guides': 'उपचार गाइड',
      'symptoms': 'लक्षण',
      'treatment_steps': 'उपचार के चरण',
      'precautions': 'सावधानियां',
      'first_aid': 'प्राथमिक चिकित्सा',
      'emergency_severe_disease': 'आपातकालीन - गंभीर बीमारी का पता चला',
      'contact_vet_immediately': 'तुरंत पशु चिकित्सक से संपर्क करें:',
      'cannot_make_call': 'कॉल नहीं कर सकते',
      'disease_fmd': 'खुरपका-मुंहपका रोग',
      'disease_mastitis': 'थनेला रोग',
      'disease_lsd': 'लंपी त्वचा रोग',
      'disease_brucellosis': 'ब्रूसीलोसिस',
      'disease_anthrax': 'एंथ्रेक्स',
      'voice_disease_prediction': 'आवाज से रोग पहचान',
      'listening_describe_symptoms': 'सुन रहे हैं... अपने पशु के लक्षण बताएं',
      'analyzing_symptoms': 'विश्लेषण कर रहे हैं...',
      'tap_mic_describe': 'माइक्रोफोन पर टैप करें और पशु के स्वास्थ्य का वर्णन करें',
      'microphone_permission_required': 'माइक्रोफोन अनुमति आवश्यक है',
      'error': 'त्रुटि',
      'speech_recognition_not_available': 'भाषण पहचान उपलब्ध नहीं है',
      'identified_disease': 'पहचाना गया रोग',
      'matched_symptoms': 'मिले लक्षण',
      'all_symptoms': 'सभी लक्षण',
      'view_treatment_guide': 'उपचार गाइड देखें',
      'stop_recording': 'रिकॉर्डिंग रोकें',
      'stop': 'रोकें',
      'start': 'शुरू करें',
      'save': 'सहेजें',
      'description_saved': 'विवरण सफलतापूर्वक सहेजा गया',
      'no_disease_identified': 'कोई रोग पहचाना नहीं गया। कृपया अधिक लक्षण बताएं।',
      'your_description_here': 'आपका विवरण यहाँ दिखाई देगा...',
      'describe_symptoms_info': 'अपने पशु के लक्षण बताएं। हम स्वचालित रूप से रोग की पहचान करेंगे।',
    },
    'ml': {
      'app_name': 'പശു ആരോഗ്യം',
      'app_subtitle': 'കന്നുകാലി ആരോഗ്യ സഹായി',
      'breed_disease_detection': 'ഇനം & രോഗ നിർണ്ണയം',
      'breed_disease_subtitle': 'ആദ്യം ഇനം തിരിച്ചറിയുക, തുടർന്ന് രോഗങ്ങൾ കണ്ടെത്തുക.',
      'treatment_guide': 'ചികിത്സാ സഹായി',
      'treatment_guide_subtitle': 'സാധാരണ ചികിത്സകൾക്കായി ഓഫ്‌ലൈൻ സഹായി ഉപയോഗിക്കുക.',
      'vet_help': 'വെറ്റ് സഹായം',
      'vet_help_subtitle': 'വിദഗ്ദ്ധ ഉപദേശത്തിനായി ഒരു വെറ്ററിനറി ഡോക്ടറുമായി ബന്ധപ്പെടുക.',
      'vet_connect_coming_soon': 'വെറ്റ് കണക്റ്റ് ഫീച്ചർ ഉടൻ വരുന്നു!',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'language': 'ഭാഷ',
      'dark_mode': 'ഡാർക്ക് മോഡ്',
      'help_support': 'സഹായം & പിന്തുണ',
      'about': 'കുറിച്ച്',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'continue_btn': 'തുടരുക',
      'choose_language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'home': 'ഹോം',
      'camera': 'ക്യാമറ',
      'gallery': 'ഗാലറി',
      'analyze': 'വിശകലനം',
      'result': 'ഫലം',
      'unknown': 'അജ്ഞാതം',
      'notifications': 'അറിയിപ്പുകൾ',
      'account': 'അക്കൗണ്ട്',
      'offline_data_update': 'ഓഫ്‌ലൈൻ ഡാറ്റ അപ്‌ഡേറ്റ്',
      'save_user_info': 'ഉപയോക്തൃ വിവരങ്ങൾ സംരക്ഷിക്കുക',
      'clear_cache': 'കാഷെ മായ്‌ക്കുക',
      'general': 'പൊതുവായ',
      'data_offline': 'ഡാറ്റ & ഓഫ്‌ലൈൻ',
      'cancel': 'റദ്ദാക്കുക',
      'clear': 'മായ്‌ക്കുക',
      'are_you_sure_clear_cache': 'കാഷെ മായ്‌ക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
      'please_select_language': 'ദയവായി ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
      'breed_detection': 'ഇനം തിരിച്ചറിയൽ',
      'breed_result': 'ഇനം ഫലം',
      'disease_detection': 'രോഗ നിർണ്ണയം',
      'detection_results': 'കണ്ടെത്തൽ ഫലങ്ങൾ',
      'upload_cattle_image': 'ഇനം തിരിച്ചറിയുന്നതിനായി നിങ്ങളുടെ കന്നുകാലിയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
      'detect_breed': 'ഇനം കണ്ടെത്തുക',
      'detecting': 'കണ്ടെത്തുന്നു...',
      'breed_identified': 'തിരിച്ചറിഞ്ഞ ഇനം',
      'confidence': 'വിശ്വാസ്യത',
      'continue_disease_detection': 'രോഗ നിർണ്ണയത്തിലേക്ക് തുടരുക',
      'upload_disease_image': 'രോഗബാധിത പ്രദേശത്തിന്റെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
      'analyze_disease': 'രോഗം വിശകലനം ചെയ്യുക',
      'analyzing': 'വിശകലനം ചെയ്യുന്നു...',
      'disease_status': 'രോഗാവസ്ഥ',
      'overall_accuracy': 'മൊത്തത്തിലുള്ള കൃത്യത',
      'no_disease_detected': 'രോഗമൊന്നും കണ്ടെത്തിയില്ല',
      'view_treatment': 'ചികിത്സ കാണുക',
      'start_new_detection': 'പുതിയ കണ്ടെത്തൽ ആരംഭിക്കുക',
      'camera_permission_required': 'ക്യാമറ അനുമതി ആവശ്യമാണ്',
      'please_capture_image': 'ദയവായി ആദ്യം ചിത്രം എടുക്കുകയോ അപ്‌ലോഡ് ചെയ്യുകയോ ചെയ്യുക',
      'breed_detection_failed': 'ഇനം കണ്ടെത്തൽ പരാജയപ്പെട്ടു',
      'disease_detection_failed': 'രോഗ നിർണ്ണയം പരാജയപ്പെട്ടു',
      'treatment_guides': 'ചികിത്സാ സഹായി',
      'symptoms': 'ലക്ഷണങ്ങൾ',
      'treatment_steps': 'ചികിത്സാ ഘട്ടങ്ങൾ',
      'precautions': 'മുൻകരുതലുകൾ',
      'first_aid': 'പ്രഥമശുശ്രൂഷ',
      'emergency_severe_disease': 'അടിയന്തരാവസ്ഥ - ഗുരുതരമായ രോഗം കണ്ടെത്തി',
      'contact_vet_immediately': 'ഉടൻ തന്നെ വെറ്ററിനറി ഡോക്ടറുമായി ബന്ധപ്പെടുക:',
      'cannot_make_call': 'കോൾ ചെയ്യാൻ കഴിയില്ല',
      'disease_fmd': 'കുളമ്പുരോഗം',
      'disease_mastitis': 'അകിടുവീക്കം',
      'disease_lsd': 'ലംപി സ്കിൻ രോഗം',
      'disease_brucellosis': 'ബ്രൂസല്ലോസിസ്',
      'disease_anthrax': 'ആന്ത്രാക്സ്',
      'voice_disease_prediction': 'ശബ്ദത്തിലൂടെ രോഗ നിർണ്ണയം',
      'listening_describe_symptoms': 'ശ്രദ്ധിക്കുന്നു... നിങ്ങളുടെ കന്നുകാലിയുടെ ലക്ഷണങ്ങൾ വിവരിക്കുക',
      'analyzing_symptoms': 'ലക്ഷണങ്ങൾ വിശകലനം ചെയ്യുന്നു...',
      'tap_mic_describe': 'കന്നുകാലിയുടെ ആരോഗ്യം വിവരിക്കാൻ മൈക്രോഫോണിൽ ടാപ്പുചെയ്യുക',
      'microphone_permission_required': 'മൈക്രോഫോൺ അനുമതി ആവശ്യമാണ്',
      'error': 'പിശക്',
      'speech_recognition_not_available': 'സംഭാഷണ തിരിച്ചറിയൽ ലഭ്യമല്ല',
      'identified_disease': 'തിരിച്ചറിഞ്ഞ രോഗം',
      'matched_symptoms': 'പൊരുത്തപ്പെടുന്ന ലക്ഷണങ്ങൾ',
      'all_symptoms': 'എല്ലാ ലക്ഷണങ്ങളും',
      'view_treatment_guide': 'ചികിത്സാ സഹായി കാണുക',
      'stop_recording': 'റെക്കോർഡിംഗ് നിർത്തുക',
      'stop': 'നിർത്തുക',
      'start': 'ആരംഭിക്കുക',
      'save': 'സംരക്ഷിക്കുക',
      'description_saved': 'വിവരണം വിജയകരമായി സംരക്ഷിച്ചു',
      'no_disease_identified': 'രോഗമൊന്നും തിരിച്ചറിഞ്ഞില്ല. ദയവായി കൂടുതൽ ലക്ഷണങ്ങൾ വിവരിക്കുക.',
      'your_description_here': 'നിങ്ങളുടെ വിവരണം ഇവിടെ ദൃശ്യമാകും...',
      'describe_symptoms_info': 'നിങ്ങളുടെ കന്നുകാലിയുടെ ലക്ഷണങ്ങൾ വിവരിക്കുക. ഞങ്ങൾ രോഗം സ്വയമേവ തിരിച്ചറിയും.',
    },
    'kn': {
      'app_name': 'ಪಶು ಸ್ವಾಸ್ಥ್ಯ',
      'app_subtitle': 'ಜಾನುವಾರು ಆರೋಗ್ಯ ಸಹಾಯಕ',
      'breed_disease_detection': 'ತಳಿ ಮತ್ತು ರೋಗ ಪತ್ತೆ',
      'breed_disease_subtitle': 'ಮೊದಲು ತಳಿಯನ್ನು ಗುರುತಿಸಿ, ನಂತರ ರೋಗಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ.',
      'treatment_guide': 'ಚಿಕಿತ್ಸಾ ಮಾರ್ಗದರ್ಶಿ',
      'treatment_guide_subtitle': 'ಸಾಮಾನ್ಯ ಚಿಕಿತ್ಸೆಗಳಿಗಾಗಿ ಆಫ್‌ಲೈನ್ ಮಾರ್ಗದರ್ಶಿಗಳನ್ನು ಬಳಸಿ.',
      'vet_help': 'ಪಶುವೈದ್ಯ ಸಹಾಯ',
      'vet_help_subtitle': 'ತಜ್ಞರ ಸಲಹೆಗಾಗಿ ಪ್ರಮಾಣೀಕೃತ ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
      'vet_connect_coming_soon': 'ವೆಟ್ ಕನೆಕ್ಟ್ ವೈಶಿಷ್ಟ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'language': 'ಭಾಷೆ',
      'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      'about': 'ಬಗ್ಗೆ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'continue_btn': 'ಮುಂದುವರಿಸಿ',
      'choose_language': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'home': 'ಮುಖಪುಟ',
      'camera': 'ಕ್ಯಾಮೆರಾ',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'analyze': 'ವಿಶ್ಲೇಷಿಸಿ',
      'result': 'ಫಲಿತಾಂಶ',
      'unknown': 'ಅಜ್ಞಾತ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'account': 'ಖಾತೆ',
      'offline_data_update': 'ಆಫ್‌ಲೈನ್ ಡೇಟಾ ನವೀಕರಣ',
      'save_user_info': 'ಬಳಕೆದಾರರ ಮಾಹಿತಿಯನ್ನು ಉಳಿಸಿ',
      'clear_cache': 'ಕ್ಯಾಶೆ ತೆರವುಗೊಳಿಸಿ',
      'general': 'ಸಾಮಾನ್ಯ',
      'data_offline': 'ಡೇಟಾ ಮತ್ತು ಆಫ್‌ಲೈನ್',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'clear': 'ತೆರವುಗೊಳಿಸಿ',
      'are_you_sure_clear_cache': 'ನೀವು ಖಂಡಿತವಾಗಿಯೂ ಕ್ಯಾಶೆ ತೆರವುಗೊಳಿಸಲು ಬಯಸುವಿರಾ?',
      'please_select_language': 'ದಯವಿಟ್ಟು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'breed_detection': 'ತಳಿ ಪತ್ತೆ',
      'breed_result': 'ತಳಿ ಫಲಿತಾಂಶ',
      'disease_detection': 'ರೋಗ ಪತ್ತೆ',
      'detection_results': 'ಪತ್ತೆ ಫಲಿತಾಂಶಗಳು',
      'upload_cattle_image': 'ತಳಿ ಗುರುತಿಸುವಿಕೆಗಾಗಿ ನಿಮ್ಮ ಜಾನುವಾರುಗಳ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      'detect_breed': 'ತಳಿ ಪತ್ತೆ ಮಾಡಿ',
      'detecting': 'ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      'breed_identified': 'ಗುರುತಿಸಲಾದ ತಳಿ',
      'confidence': 'ವಿಶ್ವಾಸಾರ್ಹತೆ',
      'continue_disease_detection': 'ರೋಗ ಪತ್ತೆಗೆ ಮುಂದುವರಿಯಿರಿ',
      'upload_disease_image': 'ರೋಗಪೀಡಿತ ಪ್ರದೇಶದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      'analyze_disease': 'ರೋಗವನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
      'analyzing': 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
      'disease_status': 'ರೋಗ ಸ್ಥಿತಿ',
      'overall_accuracy': 'ಒಟ್ಟಾರೆ ನಿಖರತೆ',
      'no_disease_detected': 'ಯಾವುದೇ ರೋಗ ಪತ್ತೆಯಾಗಿಲ್ಲ',
      'view_treatment': 'ಚಿಕಿತ್ಸೆ ವೀಕ್ಷಿಸಿ',
      'start_new_detection': 'ಹೊಸ ಪತ್ತೆ ಪ್ರಾರಂಭಿಸಿ',
      'camera_permission_required': 'ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ',
      'please_capture_image': 'ದಯವಿಟ್ಟು ಮೊದಲು ಚಿತ್ರವನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      'breed_detection_failed': 'ತಳಿ ಪತ್ತೆ ವಿಫಲವಾಗಿದೆ',
      'disease_detection_failed': 'ರೋಗ ಪತ್ತೆ ವಿಫಲವಾಗಿದೆ',
      'treatment_guides': 'ಚಿಕಿತ್ಸಾ ಮಾರ್ಗದರ್ಶಿಗಳು',
      'symptoms': 'ಲಕ್ಷಣಗಳು',
      'treatment_steps': 'ಚಿಕಿತ್ಸಾ ಹಂತಗಳು',
      'precautions': 'ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು',
      'first_aid': 'ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ',
      'emergency_severe_disease': 'ತುರ್ತು - ತೀವ್ರ ರೋಗ ಪತ್ತೆಯಾಗಿದೆ',
      'contact_vet_immediately': 'ತಕ್ಷಣ ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ:',
      'cannot_make_call': 'ಕರೆ ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ',
      'disease_fmd': 'ಕಾಲು ಬಾಯಿ ರೋಗ',
      'disease_mastitis': 'ಕೆಚ್ಚಲು ಬಾವು',
      'disease_lsd': 'ಚರ್ಮದ ಗಂಟು ರೋಗ',
      'disease_brucellosis': 'ಬ್ರೂಸೆಲೋಸಿಸ್',
      'disease_anthrax': 'ಆಂಥ್ರಾಕ್ಸ್',
      'voice_disease_prediction': 'ಧ್ವನಿ ಮೂಲಕ ರೋಗ ಪತ್ತೆ',
      'listening_describe_symptoms': 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ನಿಮ್ಮ ಜಾನುವಾರುಗಳ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ',
      'analyzing_symptoms': 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
      'tap_mic_describe': 'ಜಾನುವಾರುಗಳ ಆರೋಗ್ಯವನ್ನು ವಿವರಿಸಲು ಮೈಕ್ರೊಫೋನ್ ಟ್ಯಾಪ್ ಮಾಡಿ',
      'microphone_permission_required': 'ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ',
      'error': 'ದೋಷ',
      'speech_recognition_not_available': 'ಮಾತು ಗುರುತಿಸುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ',
      'identified_disease': 'ಗುರುತಿಸಲಾದ ರೋಗ',
      'matched_symptoms': 'ಹೊಂದಾಣಿಕೆಯ ಲಕ್ಷಣಗಳು',
      'all_symptoms': 'ಎಲ್ಲಾ ಲಕ್ಷಣಗಳು',
      'view_treatment_guide': 'ಚಿಕಿತ್ಸಾ ಮಾರ್ಗದರ್ಶಿ ವೀಕ್ಷಿಸಿ',
      'stop_recording': 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
      'stop': 'ನಿಲ್ಲಿಸಿ',
      'start': 'ಪ್ರಾರಂಭಿಸಿ',
      'save': 'ಉಳಿಸಿ',
      'description_saved': 'ವಿವರಣೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ',
      'no_disease_identified': 'ಯಾವುದೇ ರೋಗ ಪತ್ತೆಯಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಹೆಚ್ಚಿನ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ.',
      'your_description_here': 'ನಿಮ್ಮ ವಿವರಣೆ ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ...',
      'describe_symptoms_info': 'ನಿಮ್ಮ ಜಾನುವಾರುಗಳ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ. ನಾವು ರೋಗವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಗುರುತಿಸುತ್ತೇವೆ.',
    },
    'ta': {
      'app_name': 'பசு ஸ்வாஸ்த்யா',
      'app_subtitle': 'கால்நடை சுகாதார உதவியாளர்',
      'breed_disease_detection': 'இனம் மற்றும் நோய் கண்டறிதல்',
      'breed_disease_subtitle': 'முதலில் இனத்தை அடையாளம் காணவும், பின்னர் நோய்களைக் கண்டறியவும்.',
      'treatment_guide': 'சிகிச்சை வழிகாட்டி',
      'treatment_guide_subtitle': 'பொதுவான சிகிச்சைகளுக்கான ஆஃப்லைன் வழிகாட்டிகளை அணுகவும்.',
      'vet_help': 'கால்நடை உதவி',
      'vet_help_subtitle': 'நிபுணர் ஆலோசனைக்கு சான்றிதழ் பெற்ற கால்நடை மருத்துவரை அணுகவும்.',
      'vet_connect_coming_soon': 'வெட் கனெக்ட் வசதி விரைவில் வரும்!',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'dark_mode': 'டார்க் மோட்',
      'help_support': 'உதவி & ஆதரவு',
      'about': 'பற்றி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue_btn': 'தொடரவும்',
      'choose_language': 'உங்கள் மொழியைத் தேர்வுசெய்க',
      'home': 'முகப்பு',
      'camera': 'கேமரா',
      'gallery': 'கேலரி',
      'analyze': 'பகுப்பாய்வு',
      'result': 'முடிவு',
      'unknown': 'தெரியாத',
      'notifications': 'அறிவிப்புகள்',
      'account': 'கணக்கு',
      'offline_data_update': 'ஆஃப்லைன் தரவு புதுப்பிப்பு',
      'save_user_info': 'பயனர் தகவலைச் சேமி',
      'clear_cache': 'கேச் அழி',
      'general': 'பொது',
      'data_offline': 'தரவு & ஆஃப்லைன்',
      'cancel': 'ரத்துசெய்',
      'clear': 'அழி',
      'are_you_sure_clear_cache': 'நீங்கள் நிச்சயமாக கேச் அழிக்க விரும்புகிறீர்களா?',
      'please_select_language': 'தயவுசெய்து ஒரு மொழியைத் தேர்ந்தெடுக்கவும்',
      'breed_detection': 'இனக் கண்டறிதல்',
      'breed_result': 'இன முடிவு',
      'disease_detection': 'நோய் கண்டறிதல்',
      'detection_results': 'கண்டறிதல் முடிவுகள்',
      'upload_cattle_image': 'இனத்தை அடையாளம் காண உங்கள் கால்நடையின் படத்தை பதிவேற்றவும்',
      'detect_breed': 'இனத்தைக் கண்டறி',
      'detecting': 'கண்டறியப்படுகிறது...',
      'breed_identified': 'அடையாளம் காணப்பட்ட இனம்',
      'confidence': 'நம்பிக்கை',
      'continue_disease_detection': 'நோய் கண்டறிதலுக்குத் தொடரவும்',
      'upload_disease_image': 'பாதிக்கப்பட்ட பகுதியின் படத்தை பதிவேற்றவும்',
      'analyze_disease': 'நோயைப் பகுப்பாய்வு செய்',
      'analyzing': 'பகுப்பாய்வு செய்யப்படுகிறது...',
      'disease_status': 'நோய் நிலை',
      'overall_accuracy': 'ஒட்டுமொத்த துல்லியம்',
      'no_disease_detected': 'நோய் எதுவும் கண்டறியப்படவில்லை',
      'view_treatment': 'சிகிச்சையைப் பார்',
      'start_new_detection': 'புதிய கண்டறிதலைத் தொடங்கு',
      'camera_permission_required': 'கேமரா அனுமதி தேவை',
      'please_capture_image': 'தயவுசெய்து முதலில் படத்தைப் பிடிக்கவும் அல்லது பதிவேற்றவும்',
      'breed_detection_failed': 'இனக் கண்டறிதல் தோல்வியடைந்தது',
      'disease_detection_failed': 'நோய் கண்டறிதல் தோல்வியடைந்தது',
      'treatment_guides': 'சிகிச்சை வழிகாட்டிகள்',
      'symptoms': 'அறிகுறிகள்',
      'treatment_steps': 'சிகிச்சை படிகள்',
      'precautions': 'முன்னெச்சரிக்கைகள்',
      'first_aid': 'முதலுதவி',
      'emergency_severe_disease': 'அவசரம் - கடுமையான நோய் கண்டறியப்பட்டது',
      'contact_vet_immediately': 'உடனடியாக கால்நடை மருத்துவரை அணுகவும்:',
      'cannot_make_call': 'அழைக்க முடியவில்லை',
      'disease_fmd': 'கோமாரி நோய்',
      'disease_mastitis': 'மடி நோய்',
      'disease_lsd': 'தோல் கழலை நோய்',
      'disease_brucellosis': 'கருச்சிதைவு நோய்',
      'disease_anthrax': 'அடைப்பான் நோய்',
      'voice_disease_prediction': 'குரல் மூலம் நோய் கணிப்பு',
      'listening_describe_symptoms': 'கேட்கிறது... உங்கள் கால்நடையின் அறிகுறிகளை விவரிக்கவும்',
      'analyzing_symptoms': 'அறிகுறிகள் பகுப்பாய்வு செய்யப்படுகின்றன...',
      'tap_mic_describe': 'கால்நடை ஆரோக்கியத்தை விவரிக்க மைக்ரோஃபோனைத் தட்டவும்',
      'microphone_permission_required': 'மைக்ரோஃபோன் அனுமதி தேவை',
      'error': 'பிழை',
      'speech_recognition_not_available': 'பேச்சு அங்கீகாரம் கிடைக்கவில்லை',
      'identified_disease': 'அடையாளம் காணப்பட்ட நோய்',
      'matched_symptoms': 'பொருந்திய அறிகுறிகள்',
      'all_symptoms': 'அனைத்து அறிகுறிகள்',
      'view_treatment_guide': 'சிகிச்சை வழிகாட்டியைப் பார்',
      'stop_recording': 'பதிவை நிறுத்து',
      'stop': 'நிறுத்து',
      'start': 'தொடங்கு',
      'save': 'சேமி',
      'description_saved': 'விளக்கம் வெற்றிகரமாக சேமிக்கப்பட்டது',
      'no_disease_identified': 'நோய் எதுவும் அடையாளம் காணப்படவில்லை. தயவுசெய்து கூடுதல் அறிகுறிகளை விவரிக்கவும்.',
      'your_description_here': 'உங்கள் விளக்கம் இங்கே தோன்றும்...',
      'describe_symptoms_info': 'உங்கள் கால்நடையின் அறிகுறிகளை விவரிக்கவும். நாங்கள் தானாகவே நோயை அடையாளம் காண்போம்.',
    },
  };
}
