name: Release Pashu Swasthya

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: |
          flutter build apk --release
          flutter build apk --release --split-per-abi
          flutter build apk --debug

      - name: Build Android Bundle (AAB)
        run: flutter build appbundle --release

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/flutter-apk/app-release-v7a.apk,build/app/outputs/flutter-apk/app-release-v8a.apk,build/app/outputs/flutter-apk/app-release-x86_64.apk,build/app/outputs/flutter-apk/app-debug.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          draft: false
          prerelease: false
